TRAIN:
    # Number of training epochs
    epochs: 20

    # Architecture name
    arch: 'resnet50'
    # Which layer to insert AdvBN module, default: after stage-1
    cut: 1

    # Starting epoch
    start_epoch: 0

    # paramters
    optim: 'SGD'
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0001

    # Print frequency, is used for both training and testing
    print_freq: 10

    # Dataset mean and std used for data normalization
    mean: !!python/tuple [0.485, 0.456, 0.406]
    std: !!python/tuple [0.229, 0.224, 0.225]

ADV:
    # FGSM parameters during training
    scale_eps: 1.1
    fgsm_step: 0.2
    # Number of repeats for adversarial training
    n_repeats: 6

DATA:
    # Number of data workers
    workers: 16

    # Training batch size
    batch_size: 256

    # Image Size
    img_size: 256

    # Crop Size for data augmentation
    crop_size: 224

    # Color value range
    max_color_value: 255.0


